### ISSUE TITLE
404 while making images and deploying

### ISSUE THREAD

**Issue by starsunny** [kubemove/kubemove#38]
Hi Guys,
While running "make images" command, I am getting the below error. Can someone please help?
go: github.com/operator-framework/operator-sdk@v0.12.0 requires
github.com/operator-framework/operator-registry@v1.1.1 requires
bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found

@mynktl Can you please help here?

**Comment by mynktl** [comment]
Hi @starsunny 
Can you share the detailed logs?

**Comment by starsunny** [comment]
@mynktl I was trying to install kubemove using help but it was asking for updating helm repo, I have tried the same but it wasn't working in Mac. 

Then I have followed steps to deploy kubemove as mentioned in Readme.

and I am getting the below error:

**sunny@-Mac kubemove %** make images

Building base docker image for kubemove
[+] Building 3.7s (8/8) FINISHED
 => [internal] load build definition from Dockerfile-base                                                                    0.0s
 => => transferring dockerfile: 759B                                                                                         0.0s
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s
 => [internal] load metadata for docker.io/library/ubuntu:bionic                                                             3.5s
 => [1/4] FROM docker.io/library/ubuntu:bionic@sha256:ea188fdc5be9b25ca048f1e882b33f1bc763fb976a8a4fea446b38ed0efcbeba       0.0s
 => CACHED [2/4] RUN apt update && apt install -y  wget python                                                               0.0s
 => CACHED [3/4] RUN wget -O aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linu  0.0s
 => CACHED [4/4] RUN wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-272.0.0-linux-x86_64.  0.0s
 => exporting to image                                                                                                       0.0s
 => => exporting layers                                                                                                      0.0s
 => => writing image sha256:1b5fab61df8b24372ae0ddb1a39e25c601dedc9d9c2f356d791893ebb0c9d057                                 0.0s
 => => naming to 536123028970.dkr.ecr.ap-south-1.amazonaws.com/kubemove/move-base:ci                                         0.0s
Building kubemove-engine
go: github.com/operator-framework/operator-sdk@v0.12.0 requires
	github.com/operator-framework/operator-registry@v1.1.1 requires
	bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
make: *** [engine] Error 1

**Comment by sourabh-kalal** [comment]
@mynktl Is there any known issue about "helm install kubemove.io/kubemove"??

Unable to install kubemove using the helm command.

**Comment by mynktl** [comment]
> @mynktl Is there any known issue about "helm install kubemove.io/kubemove"??
> 
> Unable to install kubemove using the helm command.

@sourabh-kalal not sure about helm installation. Need to look into that. Meanwhile, can you try to install kubemove through the steps mentioned in https://github.com/kubemove/kubemove#deploy-kubemove. 
Thanks!

**Comment by mynktl** [comment]
Closing the issue with PR https://github.com/kubemove/kubemove/pull/39
